/* =========================================================
 * 星海绮谭 · 角色数据
 * 全部 60 名二次元女性角色，含品质 / 类型 / 气质 / 元素 / 小传
 * implemented:true 表示已绘制立绘、进入抽卡池（当前 60 名全部实装）
 * ========================================================= */

const RARITY = {
  R:   { key: 'R',   label: 'R',   rate: 0.792, color: '#5aa9e6', glow: 'rgba(90,169,230,.9)',  stars: 3 },
  SR:  { key: 'SR',  label: 'SR',  rate: 0.200, color: '#b06bff', glow: 'rgba(176,107,255,.9)', stars: 4 },
  SSR: { key: 'SSR', label: 'SSR', rate: 0.008, color: '#ffcf5c', glow: 'rgba(255,207,92,1)',   stars: 5 },
};

const CATEGORIES = {
  '机甲': { icon: '⚙️', color: '#67d5ff' },
  '校园': { icon: '🌸', color: '#ff9ec7' },
  '魔法': { icon: '✦',  color: '#b48bff' },
  '冒险': { icon: '⚔️', color: '#ffc46b' },
};

/* 数值随品质浮动，仅用于图鉴展示游戏感 */
const CHARACTERS = [
  /* ===================== 机甲 (15) ===================== */
  { id:1,  name:'星澜',   title:'苍穹统帅',   rarity:'SSR', category:'机甲', vibe:'性感', element:'星辰', hp:9800, atk:2480, implemented:true,
    bio:'曾是联邦最年轻的舰队司令，却因拒绝下达屠城令而被通缉。她驾驶旗舰「苍澜」流亡星海，坚信武力只为守护而非征服。冷艳外表之下，是一颗甘愿为部下燃尽自己的心。' },
  { id:2,  name:'缇娜',   title:'绯红尖兵',   rarity:'SSR', category:'机甲', vibe:'少女', element:'火',   hp:8600, atk:2620, implemented:true,
    bio:'孤儿院出身的天才机师，十四岁便击落了王牌中队。她固执地把座机涂成最显眼的绯红——「不想再有人在战场上找不到我」。笑起来像个孩子，扣下扳机时却毫不犹豫。' },
  { id:3,  name:'玲音',   title:'零号机魂',   rarity:'SSR', category:'机甲', vibe:'清纯', element:'机械', hp:9200, atk:2400, implemented:true,
    bio:'实验室中诞生的人机融合体，编号 ZERO。她不懂何为眼泪，却会在雨夜独自伸手去接雨滴。「如果我能感受到痛，是不是就离人类更近一点？」——她这样问，没有人回答。' },
  { id:4,  name:'钢羽',   title:'机械之翼',   rarity:'SR',  category:'机甲', vibe:'英气', element:'风',   hp:6400, atk:1860, implemented:true,
    bio:'佣兵公司的金牌飞行员，背负一对可拆卸的合金机翼。她信奉「契约高于一切」，却总在合约之外多救几个人。' },
  { id:5,  name:'蓝芯',   title:'深蓝芯核',   rarity:'SR',  category:'机甲', vibe:'少女', element:'水',   hp:6100, atk:1720, implemented:true,
    bio:'天才少女工程师，能与任何机械「对话」。口头禅是「交给我，三分钟搞定」，然后埋头修了三小时——但东西真的会被她修好。' },
  { id:6,  name:'赤夜',   title:'暗夜突袭',   rarity:'SR',  category:'机甲', vibe:'性感', element:'暗',   hp:5900, atk:1980, implemented:true,
    bio:'夜战特化的潜入型机师，行动时如影随形。白天慵懒贪睡，入夜便化身致命猎手。' },
  { id:7,  name:'银狼',   title:'银狼队长',   rarity:'SR',  category:'机甲', vibe:'成熟', element:'雷',   hp:6700, atk:1800, implemented:true,
    bio:'陆战机甲小队的女队长，治军严明。队员们怕她，更敬她——因为她永远第一个冲锋，最后一个撤退。' },
  { id:8,  name:'诺娃',   title:'新星推进',   rarity:'SR',  category:'机甲', vibe:'少女', element:'光',   hp:5800, atk:1760, implemented:true,
    bio:'学院刚毕业的见习机师，热血又莽撞。梦想是成为「像传说中那样」的英雄——哪怕现在连平稳降落都还会摔个跟头。' },
  { id:9,  name:'铁铃',   title:'巡逻铁卫',   rarity:'R',   category:'机甲', vibe:'清纯', element:'机械', hp:3600, atk:980,  implemented:true,
    bio:'边境哨站的普通巡逻兵，日复一日守着没人会来的关口。她把每一次例行巡逻，都当成天大的事认真对待。' },
  { id:10, name:'雀斑',   title:'维修班长',   rarity:'R',   category:'机甲', vibe:'少女', element:'机械', hp:3400, atk:920,  implemented:true,
    bio:'机库里最吵的姑娘，满脸机油也挡不住笑容。「没有我修不好的机甲，只有我没睡醒的早晨。」' },
  { id:11, name:'砂',     title:'沙漠游骑',   rarity:'R',   category:'机甲', vibe:'英气', element:'土',   hp:3700, atk:1010, implemented:true,
    bio:'沙漠运输队的护卫，沉默寡言。她能在漫天沙暴里，凭引擎的轰鸣分辨敌我。' },
  { id:12, name:'寒霜',   title:'极地哨兵',   rarity:'R',   category:'机甲', vibe:'清纯', element:'冰',   hp:3500, atk:940,  implemented:true,
    bio:'驻守极地基地的观测员，早已习惯与冰雪和孤独为伴。她说，极光是寂寞的人才看得懂的信。' },
  { id:13, name:'火花',   title:'见习炮手',   rarity:'R',   category:'机甲', vibe:'少女', element:'火',   hp:3300, atk:1040, implemented:true,
    bio:'重火力机甲的实习炮手，总把巨大的后坐力当成「机甲在跟我击掌」。她的耳朵被震得不太好使，笑容却一天比一天大。' },
  { id:14, name:'锈月',   title:'废铁猎人',   rarity:'R',   category:'机甲', vibe:'性感', element:'机械', hp:3800, atk:990,  implemented:true,
    bio:'在废弃战场捡破烂为生的拾荒者，却能把一堆废铁拼成能上场的机甲。「别人的垃圾，是我的勋章。」' },
  { id:15, name:'微光',   title:'信号兵',     rarity:'R',   category:'机甲', vibe:'清纯', element:'光',   hp:3200, atk:900,  implemented:true,
    bio:'负责战场通讯的信号兵，她的声音，是无数士兵在绝境中听到的最后一丝慰藉。' },

  /* ===================== 校园 (15) ===================== */
  { id:16, name:'樱小路·雪', title:'学生会长', rarity:'SSR', category:'校园', vibe:'清纯', element:'光', hp:8400, atk:2300, implemented:true,
    bio:'完美无缺的学生会长，成绩、容貌、家世样样顶尖。可只有天台的猫知道，她午休时会偷偷躲起来啃廉价的便利店饭团。「当一个完美的人，好累啊。」' },
  { id:17, name:'绫濑·灯',   title:'不良少女', rarity:'SSR', category:'校园', vibe:'性感', element:'火', hp:8800, atk:2520, implemented:true,
    bio:'校内闻风丧胆的太妹头子，逃课打架样样精通。但她偷偷资助着三个孤儿弟妹，每次出手也只为护着被欺负的人。「别误会，我可不是什么好人。」' },
  { id:18, name:'星野·澪',   title:'天文部长', rarity:'SR',  category:'校园', vibe:'清纯', element:'星辰', hp:6000, atk:1680, implemented:true,
    bio:'独守天文部的安静女孩，能叫出夜空中每一颗星的名字。她在等一颗百年一遇的彗星——也在等一个愿意陪她一起等下去的人。' },
  { id:19, name:'桃濑·萌',   title:'应援团长', rarity:'SR',  category:'校园', vibe:'少女', element:'风', hp:5700, atk:1640, implemented:true,
    bio:'全校最有活力的啦啦队长，嗓门大、笑点低。「输赢不重要，但气势绝对不能输！」' },
  { id:20, name:'冬月·凛',   title:'剑道主将', rarity:'SR',  category:'校园', vibe:'英气', element:'雷', hp:6300, atk:1900, implemented:true,
    bio:'剑道部的冷面主将，一击必中。她把所有情绪都收进剑鞘，只在胜负的一瞬，才肯流露出锋芒。' },
  { id:21, name:'美咲·甜',   title:'烹饪研究部', rarity:'SR', category:'校园', vibe:'丰满', element:'火', hp:6200, atk:1600, implemented:true,
    bio:'烹饪研究部的招牌，做的甜点能让人幸福到落泪。她的梦想，是开一家「让所有人都笑着离开」的小店。' },
  { id:22, name:'水濑·凉',   title:'游泳部王牌', rarity:'SR', category:'校园', vibe:'性感', element:'水', hp:5900, atk:1700, implemented:true,
    bio:'游泳部的王牌，泳池里的人鱼。阳光开朗，唯独怕黑——所以训练总拖到最后一个走，又总要拉个人陪她。' },
  { id:23, name:'小鸟游·音', title:'轻音部', rarity:'R', category:'校园', vibe:'少女', element:'风', hp:3300, atk:880, implemented:true,
    bio:'轻音部吉他手，舞台上闪闪发光，台下却是个会紧张到躲进储物间的内向女孩。' },
  { id:24, name:'日向·暖',   title:'图书委员', rarity:'R', category:'校园', vibe:'清纯', element:'光', hp:3200, atk:840, implemented:true,
    bio:'总在图书馆角落看书的眼镜少女，记得馆里每一本书的位置，唯独不知道该怎么开口交朋友。' },
  { id:25, name:'早濑·跑',   title:'田径部', rarity:'R', category:'校园', vibe:'少女', element:'风', hp:3400, atk:900, implemented:true,
    bio:'田径部的短跑选手，风一样的女孩。「追不上也没关系，反正我跑得比烦恼快。」' },
  { id:26, name:'紫苑·静',   title:'美术部', rarity:'R', category:'校园', vibe:'清纯', element:'暗', hp:3100, atk:860, implemented:true,
    bio:'美术部的画痴，眼里只有光影与色彩。她画遍了全校的角落，却始终不敢落笔，画下心仪之人的脸。' },
  { id:27, name:'柚子·酸',   title:'园艺部', rarity:'R', category:'校园', vibe:'少女', element:'木', hp:3000, atk:820, implemented:true,
    bio:'打理校园花圃的园艺少女，和植物说话比和人多。她种的向日葵，永远朝着那间教室的方向。' },
  { id:28, name:'真白·雪',   title:'神秘转学生', rarity:'R', category:'校园', vibe:'清纯', element:'冰', hp:3500, atk:920, implemented:true,
    bio:'学期中途突然出现的转学生，话很少，笔记却借给了每一个需要的人。没人知道她从哪来，又要到哪去。' },
  { id:29, name:'铃兰·铃',   title:'广播部', rarity:'R', category:'校园', vibe:'少女', element:'光', hp:3200, atk:880, implemented:true,
    bio:'午间广播的声音主人，治愈了无数午睡的灵魂。可没有人见过，广播室里的她究竟长什么模样。' },
  { id:30, name:'七濑·梦',   title:'留级生姐姐', rarity:'R', category:'校园', vibe:'丰满', element:'火', hp:3700, atk:960, implemented:true,
    bio:'比同班同学大两岁的留级生姐姐，看似吊儿郎当，关键时刻却最靠谱，是全班公认的「妈妈」。' },

  /* ===================== 魔法 (15) ===================== */
  { id:31, name:'薇薇安', title:'深红魔女', rarity:'SSR', category:'魔法', vibe:'性感', element:'火', hp:9000, atk:2700, implemented:true,
    bio:'被禁忌之书选中的红发魔女，掌握足以焚城的火焰。她周游列国寻找解咒之法——因为每施展一次大魔法，她的寿命就会缩短一分。' },
  { id:32, name:'莉莉丝', title:'月之神官', rarity:'SSR', category:'魔法', vibe:'清纯', element:'光', hp:8700, atk:2350, implemented:true,
    bio:'月神殿最后的巫女，能聆听亡者的低语。她独自背负着安抚整个王国哀魂的使命，从不喊一声累。' },
  { id:33, name:'诺克缇丝', title:'虚空咏者', rarity:'SSR', category:'魔法', vibe:'性感', element:'暗', hp:9100, atk:2680, implemented:true,
    bio:'操纵虚空与暗影的堕落贤者，曾是光明教廷的圣女。当她目睹「神」的真面目，便毅然撕碎圣袍走向黑暗——「若光明会撒谎，我宁愿拥抱黑夜」。' },
  { id:34, name:'艾拉',   title:'见习炼金师', rarity:'SR', category:'魔法', vibe:'少女', element:'木', hp:5800, atk:1620, implemented:true,
    bio:'炼金工坊的迷糊学徒，炸坏的坩埚比成功的药剂还多。但她坚信「失败一百次，那第一百零一次就是奇迹」。' },
  { id:35, name:'芙萝拉', title:'花之妖精', rarity:'SR', category:'魔法', vibe:'少女', element:'木', hp:5600, atk:1580, implemented:true,
    bio:'森林深处的花妖精，会用花粉治愈伤口。她打心底里讨厌战争，却为了守护森林，硬是学会了战斗。' },
  { id:36, name:'赛琳娜', title:'海之歌姬', rarity:'SR', category:'魔法', vibe:'性感', element:'水', hp:5900, atk:1700, implemented:true,
    bio:'海妖血统的吟游诗人，歌声能掀起风暴，也能抚平惊涛。她踏遍海岸，只为寻找传说中那座沉没的故乡。' },
  { id:37, name:'葛蕾丝', title:'圣盾骑士', rarity:'SR', category:'魔法', vibe:'丰满', element:'光', hp:6800, atk:1560, implemented:true,
    bio:'教会的圣盾骑士，以守护为天职。她的盾后藏过太多人，唯独没给自己留过一条退路。' },
  { id:38, name:'茜',     title:'东国阴阳师', rarity:'SR', category:'魔法', vibe:'清纯', element:'暗', hp:5700, atk:1660, implemented:true,
    bio:'东方来的年轻阴阳师，身边跟着一只九尾式神。她降妖除魔，却总忍不住对走投无路的妖怪心软。' },
  { id:39, name:'蜜朵',   title:'药草师', rarity:'R', category:'魔法', vibe:'少女', element:'木', hp:3100, atk:840, implemented:true,
    bio:'村口药铺的姑娘，认得山里每一株草。她的梦想很小：让村里再没有人，因为生病而离开。' },
  { id:40, name:'露娜',   title:'占星学徒', rarity:'R', category:'魔法', vibe:'清纯', element:'星辰', hp:3000, atk:820, implemented:true,
    bio:'占星塔的学徒，能从星图读出明日的天气，却始终读不懂自己的那点心事。' },
  { id:41, name:'茉莉',   title:'召唤新手', rarity:'R', category:'魔法', vibe:'少女', element:'风', hp:3200, atk:860, implemented:true,
    bio:'总是召唤错生物的召唤师菜鸟。本想召唤一头巨龙，结果来了只会喷火的小蜥蜴——她俩反倒成了最好的搭档。' },
  { id:42, name:'黛西',   title:'符文匠', rarity:'R', category:'魔法', vibe:'清纯', element:'土', hp:3300, atk:880, implemented:true,
    bio:'刻写符文的工匠少女，一笔一画都极其认真。「潦草的符文，是会要人命的。」' },
  { id:43, name:'雪莉',   title:'冰晶法师', rarity:'R', category:'魔法', vibe:'清纯', element:'冰', hp:3400, atk:900, implemented:true,
    bio:'性格高冷的冰系法师，说起话来像冰碴子扎人，却会偷偷给冻僵的流浪猫，搭一座小小的冰屋。' },
  { id:44, name:'琥珀',   title:'兽语者', rarity:'R', category:'魔法', vibe:'少女', element:'木', hp:3100, atk:850, implemented:true,
    bio:'能听懂野兽语言的少女，森林是她的家，野狼是她的玩伴。她说人类的语言太复杂，远不如一声狼嚎来得真诚。' },
  { id:45, name:'烟霞',   title:'香炉术士', rarity:'R', category:'魔法', vibe:'性感', element:'火', hp:3500, atk:920, implemented:true,
    bio:'以异香操控人心的术士，神秘莫测。她说，每一缕香的背后，都藏着一个不愿被人知道的故事。' },

  /* ===================== 冒险 (15) ===================== */
  { id:46, name:'维罗妮卡', title:'黄金船长', rarity:'SSR', category:'冒险', vibe:'性感', element:'水', hp:9300, atk:2560, implemented:true,
    bio:'纵横七海的女海盗船长，悬赏金高得能买下一座城。她劫富济贫、放荡不羁，唯一的铁律是——「我的船上，绝不准有奴隶」。' },
  { id:47, name:'阿斯特蕾', title:'屠龙剑圣', rarity:'SSR', category:'冒险', vibe:'英气', element:'雷', hp:9500, atk:2640, implemented:true,
    bio:'独自斩杀过三头古龙的剑圣，背负着灭族之仇。她的剑很快，心却很慢——慢到至今没能学会，如何放下仇恨。' },
  { id:48, name:'凯特',   title:'百步神射', rarity:'SR', category:'冒险', vibe:'少女', element:'风', hp:5800, atk:1740, implemented:true,
    bio:'百步穿杨的赏金弓手，性子跳脱爱吹牛。但她吹过的每一个牛皮，最后竟都一一射中了靶心。' },
  { id:49, name:'罗莎',   title:'盗宝猎人', rarity:'SR', category:'冒险', vibe:'性感', element:'暗', hp:5700, atk:1680, implemented:true,
    bio:'游走于遗迹与陷阱之间的盗宝者，机敏狡黠。「宝藏是死的，命是自己的」——这是她活到现在的全部秘诀。' },
  { id:50, name:'海蒂',   title:'见习龙骑', rarity:'SR', category:'冒险', vibe:'英气', element:'火', hp:6200, atk:1820, implemented:true,
    bio:'与一头幼龙签订契约的见习龙骑士，骄傲又热血。她发誓要带着伙伴飞上云层之上，去看一看龙族的故乡。' },
  { id:51, name:'布兰雅', title:'雪山向导', rarity:'SR', category:'冒险', vibe:'清纯', element:'冰', hp:5600, atk:1600, implemented:true,
    bio:'雪山脚下的向导少女，熟悉每一条隐秘山路。她送过无数旅人翻越雪山，自己却从未走出过这座山。' },
  { id:52, name:'茱莉',   title:'吟游旅人', rarity:'SR', category:'冒险', vibe:'少女', element:'光', hp:5500, atk:1560, implemented:true,
    bio:'背着鲁特琴四处流浪的吟游诗人，走到哪唱到哪。她收集着别人的故事，自己也成了别人故事里的一段插曲。' },
  { id:53, name:'妮娜',   title:'见习冒险者', rarity:'R', category:'冒险', vibe:'少女', element:'火', hp:3300, atk:900, implemented:true,
    bio:'刚拿到冒险者执照的新人，揣着攒了三年的盘缠和满脑子英雄梦，踏上了旅途。她的剑还很钝，眼睛却很亮。' },
  { id:54, name:'葛萝',   title:'旅店老板娘', rarity:'R', category:'冒险', vibe:'丰满', element:'火', hp:3800, atk:860, implemented:true,
    bio:'冒险者公会旁那家小旅店的老板娘，见惯了来来往往的英雄与懦夫。她的麦酒，和她的忠告一样浓烈。' },
  { id:55, name:'琪琪',   title:'信使少女', rarity:'R', category:'冒险', vibe:'少女', element:'风', hp:3200, atk:880, implemented:true,
    bio:'骑着扫帚送信的快递少女，使命必达。再远的地方、再急的信，只要交给她，那就准没错。' },
  { id:56, name:'塔比',   title:'陷阱师', rarity:'R', category:'冒险', vibe:'清纯', element:'土', hp:3100, atk:840, implemented:true,
    bio:'擅长拆解机关的工匠，队伍里最不起眼、也最不可或缺的那个人。「英雄负责潇洒，我负责让他们活着潇洒。」' },
  { id:57, name:'苏茜',   title:'草药采集者', rarity:'R', category:'冒险', vibe:'清纯', element:'木', hp:3000, atk:820, implemented:true,
    bio:'在野外采集珍稀药材的少女，胆小却执着。为了一株悬崖上的雪莲，她能屏着呼吸蹲上一整天。' },
  { id:58, name:'蕾娜',   title:'流浪剑客', rarity:'R', category:'冒险', vibe:'英气', element:'暗', hp:3600, atk:940, implemented:true,
    bio:'居无定所的流浪剑客，以剑换饭。她走过太多地方，只为寻找一个，能让她停下脚步的理由。' },
  { id:59, name:'多萝',   title:'矿洞探险家', rarity:'R', category:'冒险', vibe:'少女', element:'土', hp:3200, atk:860, implemented:true,
    bio:'痴迷地下宝石的矿洞探险家，眼里的光，比她头顶的矿灯还要亮上几分。' },
  { id:60, name:'菲比',   title:'篝火诗人', rarity:'R', category:'冒险', vibe:'清纯', element:'火', hp:3100, atk:830, implemented:true,
    bio:'总在营地篝火旁出现的神秘少女，为疲惫的旅人唱起安眠的歌。天一亮，她又消失在了晨雾里。' },
];

/* 便捷查询 */
const CHAR_BY_ID = Object.fromEntries(CHARACTERS.map(c => [c.id, c]));
const POOL = CHARACTERS.filter(c => c.implemented); // 抽卡池：仅已实装角色

window.GameData = { RARITY, CATEGORIES, CHARACTERS, CHAR_BY_ID, POOL };
